config/routes.rb
Rails.application.routes.draw do
    get 'tournament/index', as: 'tournaments'
    get 'team/index', as: 'teams'
    get 'player/index', as: 'players'

    get 'tournament_team/index'

    get 'tournament_team/create'

    get 'tournament_team/show'

    get 'tournament_player/index'

    get 'tournament_player/create'

    get 'tournament_player/show'

    get 'team/create'

    get 'team/show'

    get 'player/create'

    get 'player/show'

    post 'tournament/create', to: 'tournament#create', as: 'create_tournament'

    get 'tournament/new'

    get 'tournament/show'

    root 'welcome#home'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :tournament_team
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  def self.search(params)
    if params
      @found_tournaments = ActiveRecord::Base.connection.execute("SELECT * from tournaments where tournaments.tournament_name like '#{params['tournament_name']}%'")
      @found_tournaments ? @found_tournaments : nil
    else
      nil
    end
  end

  def self.create_tournament(params)
    if params
      @tournament = ActiveRecord::Base.connection.execute("INSERT INTO 'tournaments' ('tournament_name', 'created_at', 'updated_at') VALUES('#{params['tournament_name']}', '#{Time.now}', '#{Time.now}')")
    else
      nil
    end
  end

end

app/models/tournament_player.rb
class TournamentPlayer < ApplicationRecord
  belongs_to :tournament
end

app/models/tournament_team.rb
class TournamentTeam < ApplicationRecord
  belongs_to :tournament
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def index
  end

  def create
  end

  def show
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end

  def create
  end

  def show
  end
end

app/controllers/tournament_controller.rb
class TournamentController < ApplicationController
  def new
    @tournament = Tournament.new
  end

  def index
    @tournaments = Tournament.all
    if params[:tournament_name]
      @search = {
        'tournament_name' => params[:tournament_name]
      }
    end
    @found_tournaments = Tournament.search(@search)
  end

  def create
    @tournament = Tournament.create_tournament(tournment_params)
    redirect_to tournaments_path
  end

  def show
  end

  def tournment_params
    params.require(:tournament).permit(:tournament_name)
  end
end

app/controllers/tournament_player_controller.rb
class TournamentPlayerController < ApplicationController
  def index
  end

  def create
  end

  def show
  end
end

app/controllers/tournament_team_controller.rb
class TournamentTeamController < ApplicationController
  def index
  end

  def create
  end

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/tournament_helper.rb
module TournamentHelper
end

app/helpers/tournament_player_helper.rb
module TournamentPlayerHelper
end

app/helpers/tournament_team_helper.rb
module TournamentTeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FootballClub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/player/create.html.erb
<h1>Player#create</h1>
<p>Find me in app/views/player/create.html.erb</p>

app/views/player/index.html.erb
<h1>Player#index</h1>
<p>Find me in app/views/player/index.html.erb</p>

app/views/player/show.html.erb
<h1>Player#show</h1>
<p>Find me in app/views/player/show.html.erb</p>

app/views/team/create.html.erb
<h1>Team#create</h1>
<p>Find me in app/views/team/create.html.erb</p>

app/views/team/index.html.erb
<h1>Team#index</h1>
<p>Find me in app/views/team/index.html.erb</p>

app/views/team/show.html.erb
<h1>Team#show</h1>
<p>Find me in app/views/team/show.html.erb</p>

app/views/tournament/index.html.erb
<div class="container-fluid tournaments">
    <div class="tournaments-container">
        <div class="col-md-1">
            <div class="tournaments-button-wrapper">
                <%= link_to tournament_new_path  do %>
                <span class="icon icon-circle">
                    <span class="glyphicon glyphicon-plus" title="New tournament"></span>
                </span>
                <% end %>
            </div>
            <div class="tournaments-button-wrapper">
                <%= link_to root_path do %>
                <span class="icon icon-circle">
                    <span class="glyphicon glyphicon-chevron-left" title="Back"></span>
                </span>
                <% end %>
            </div>
        </div>
        <div class="tournaments-found col-md-5 col-md-offset-1">
            <div class="container">
                <div class="col-md-6">
                    <h2 class="tournaments-header">
                        Let's search:
                    </h2>
                    <%= form_tag(tournaments_path, method: :get, class: 'tournaments-form-search') do %>
                    <div class="form-line-wrapper">
                        <div class="col-md-4">
                            <label class="form-label">Tournament name:</label>
                        </div>
                        <div class="col-md-8">
                            <%= text_field_tag :tournament_name, "", class: 'form-input' %>
                        </div>
                    </div>
                    <div class="col-md-6 col-md-offset-3">
                        <%= submit_tag 'Search', class: 'btn btn-success form-submit tournaments-button-wrapper' %>
                    </div>
                    <% end %>
                    <% if @found_tournaments != nil and @found_tournaments.size > 0 %>
                    <h2 class="tournaments-header">
                        Found tournaments:
                    </h2>
                    <table class="tournaments-table">
                        <tr>
                            <td>ID</td>
                            <td>Tournament Name</td>
                        </tr>
                        <% @found_tournaments.each do |tournament| %>
                        <tr>
                            <td>
                                <%= tournament['tournament_id'] %>
                            </td>
                            <td>
                                <%= tournament['tournament_name'] %>
                            </td>
                        </tr>
                        <% end %>
                    </table>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="tournaments-all">
                <div class="container">
                    <% if @tournaments %>
                    <h2 class="tournaments-header">
                        List of tournaments:
                    </h2>
                    <table class="tournaments-table">
                        <tr>
                            <td>ID</td>
                            <td>Tournament Name</td>
                        </tr>
                        <% @tournaments.each do |tournament| %>
                        <tr>
                            <td>
                                <%= tournament.tournament_id %>
                            </td>
                            <td>
                                <%= tournament.tournament_name %>
                            </td>
                        </tr>
                        <% end %>
                    </table>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/tournament/new.html.erb
<div class="container">
	<div class="tournaments-new">
		<div class="tournaments-new-header">
			<h1>Create tournament</h1>
		</div>
		<%= form_for @tournament,
			url: create_tournament_path do |f| %>
			<div class="form-fields">
				<div class="name-field">
					<%= f.text_field :tournament_name,
						placeholder: "Tournament name ...",
						class: "form-input",
						required: true %>
				</div>
			</div>
			<div class="button-group">
				<%= f.submit "Create", class: "btn btn-success" %>
				<%= link_to 'Back', tournaments_path, class: "btn btn-primary" %>
			</div>
		<% end %>
	</div>
</div>

app/views/tournament/show.html.erb
<h1>Tournament#show</h1>
<p>Find me in app/views/tournament/show.html.erb</p>

app/views/tournament_player/create.html.erb
<h1>TournamentPlayer#create</h1>
<p>Find me in app/views/tournament_player/create.html.erb</p>

app/views/tournament_player/index.html.erb
<h1>TournamentPlayer#index</h1>
<p>Find me in app/views/tournament_player/index.html.erb</p>

app/views/tournament_player/show.html.erb
<h1>TournamentPlayer#show</h1>
<p>Find me in app/views/tournament_player/show.html.erb</p>

app/views/tournament_team/create.html.erb
<h1>TournamentTeam#create</h1>
<p>Find me in app/views/tournament_team/create.html.erb</p>

app/views/tournament_team/index.html.erb
<h1>TournamentTeam#index</h1>
<p>Find me in app/views/tournament_team/index.html.erb</p>

app/views/tournament_team/show.html.erb
<h1>TournamentTeam#show</h1>
<p>Find me in app/views/tournament_team/show.html.erb</p>

app/views/welcome/home.html.erb
<div class="container-fluid home">
    <div class="container">
        <h1 class="text-center home-header">
            Football club manager
        </h1>
        <h2 class="home-subheader">
            Choose table for manipulation:
        </h2>

        <div class="container home-container">
            <div class="col-md-4">
                <%= link_to 'Tournaments', tournaments_path, class: 'button button-red' %>
            </div>
            <div class="col-md-4">
                <%= link_to 'Players', players_path, class: 'button button-red' %>
            </div>
            <div class="col-md-4">
                <%= link_to 'Teams', teams_path, class: 'button button-red' %>
            </div>
        </div>
    </div>
</div>